### ISSUE TITLE
系统主题里的资源能替换吗？比如说toolbar里的弹出框以及沉浸页面的状态栏的切换要怎么替换？自定义processor吗？

### ISSUE THREAD

**Issue by eity0323** [hack2ware/injor#1]
系统主题里的资源能替换吗？比如说toolbar里的弹出框以及沉浸页面的状态栏的切换要怎么替换？自定义processor吗？

**Comment by hackware1993** [comment]
@eity0323 额，不能的

**Comment by hackware1993** [comment]
我想了想，可以的

**Comment by eity0323** [comment]
@hackware1993 解决思路是什么？我绕过了这个问题，自定义类似toolbar组件的功能，就能自己控制样式了

**Comment by hackware1993** [comment]
@eity0323 你需要通过id找到toolbar里的元素，为这些元素设置tag，再injectSkin
